import MenuItems from "./MenuItems";
import NativeBalance from "./NativeBalance";
import Chains from "./Chains/Chains";
import Account from "./Account/Account";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-32">
        <header className="flex justify-between items-center">
          <MenuItems />
          <div className="flex space-x-5 items-center py-5">
            <Chains />
            <NativeBalance />
            <Account />
          </div>
        </header>
        <hr />
        {children}
      </div>
    </>
  );
};

export default Layout;
